# Generated by Django 4.0.3 on 2022-04-10 17:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='autor',
            field=ckeditor.fields.RichTextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitulo',
            field=ckeditor.fields.RichTextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='titulo',
            field=ckeditor.fields.RichTextField(max_length=50),
        ),
    ]
