# Generated by Django 4.0.3 on 2022-04-10 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_autor_alter_blog_subtitulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
